baseURL = "https://dashdashzako.github.io/hugo-journal-demo/"
languageCode = "en-us"
title = "Hugo Journal Theme Showcase"
theme = "journal"

[params]
  AuthorName = "dashdashzako"
  GithubUsername = "dashdashzako"
  Tagline = "Minimalist theme for Hugo"
  mainSections = ["post"]
